### ISSUE TITLE
project

### ISSUE THREAD

**Issue by mrutu** [paceuniversity/gsd2014-team3#19]
can you help me shortly about GitHub because i want to know more about it.

**Comment by csakai** [comment]
In order to understand GitHub, once must first understand Git.

Git is a version control system created and named by Linus Torvald. It is designed to manage and track projects throughout development and production. At the start of a project, the developer creates a "Git Repository", which is where all development files, etc are compressed and makred with a hash denoting when it was made, by who, etc. Whenever the developer reaches a milestone, such as implementing a form on a web page, they commit these changes to their git repository. This is different from the typical saving changes, because this is a new version of the development project. You can track these changes, and in case of an issue, you can rollback to previous commits.

Git also allows the developer to create "branches" from the repo. This allows them to work on a new feature and track it while not actually affecting the way previous working commits function. Once that branch has been tested and works successfully, the developer can simply merge it back into the main branch, and now the full project will include it.

There is more to the nuance of Git and I recommend looking into Pro Git, a free ebook that explains how Git works and is an excellent resource. http://git-scm.com/book

Now, GitHub itself is a little bit simpler if you understand how Git works.

GitHub is simply a networked site that gives a developer a remote to store their repositories. This is extremely beneficial to a developer, especially if he or she is working with other developers. They can all work on separate parts of a project and push their changes to their GitHub repo. It is considered a "remote", and how to use that can be found in the Pro Git Book I mentioned earlier. It's also explained on the GitHub site itself.

GitHub also has the added benefit of a more user-friendly interface than simply using the command line to manipulate Git repositories, as well as advanced features like Issues, Wikis, and analytic graphs.

**Comment by mrutu** [comment]
thanks for this small lecture it's my time to lean more about Github
through  given website.
