### ISSUE TITLE
project

### ISSUE THREAD

**Issue by mrutu** [paceuniversity/gsd2014-team3#20]
can you give me shortly briefly about json

**Comment by csakai** [comment]
JSON or JavaScript Object Notation is a method for storing and transferring data. It is very much like XML, but it has a different syntax.
Instead of having markup documents, we have "JSON Documents". The easiest way to show this is by example.
Let's say I want to create a JSON document to describe myself. Here is what it would look like:
{ "name": "Chris Sakai",
  "age": 23,
  "occupation": "Student" }

As you can see, it uses key-value pairs to organize the data. By the key "name", I'm given the value "Chris Sakai", etc.
Because JSON is just JavaScript, its values are all made with JavaScript typing. So, my name "Chris Sakai" and occupation "Student" are Strings. My age 23 is an int.

If you're familiar with JavaScript, you'll notice the syntax of a JSON document is identical to a JavaScript Object. All JSON documents are JavaScript Objects without methods/functions.

JSON documents' values can hold any JavaScript type, even arrays and other JSON documents.
Any JavaScript library (like jQuery, which we'll be using) will have functions built in for Parsing and creating JSON documents. Let's use a basic example.

var obj = jQuery.parseJSON( '{ "name": "Chris Sakai", "age":23, "occupation": "Student" }' );
alert( obj.name);

What this will do is parse my JSON document and store it in the variable "obj". Then it will reach into the "obj" variable and grab whatever is in the "name" field, in this case "Chris Sakai". Then it pops up an alert dialog box that just says "Chris Sakai".

We'll go more in depth about JSON and using it since it makes sense to use it for our project.

For example: 
{ "english": "hello", "kiswahili": "hujambo" }

Using that document will make it very easy to include the words we teach in the dictionary of our app.

Let me know if you need any further clarification. If you wish to take a more technical look at JSON, here is the JSON Spec: http://www.json.org/
